INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	1,	1	, "AGC"	, "Anola Golf Club");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	2,	2	, "SCG"	, "Santa Claus Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	3,	3	, "AulG"	, "Aulanko Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	4,	4	, "AG"	, "Aura Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	5,	5	, "BG"	, "Botnia Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	6,	6	, "EGs"	, "Espoon Golfseura");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	7,	7	, "ERG"	, "Espoo Ringside Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	8,	8	, "EPG"	, "Etelä-Pohjanmaan Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	9,	9	, "G-P"	, "Golf-Porrassalmi");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	10,	10	, "GT"	, "Golf Talma");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	11,	11	, "G-V"	, "Golf-Virrat");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	12,	12	, "GG"	, "Gumböle Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	13,	13	, "HG"	, "Hangon Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	14,	14	, "HkGk"	, "Hartolan Golfklubi");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	15,	15	, "HeGk"	, "Helsingin Golfklubi");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	16,	16	, "HkG"	, "Hiekkaharju Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	18,	18	, "HyG"	, "Hyvinkään Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	19,	19	, "IkG"	, "Ikaalisten Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	20,	20	, "ImG"	, "Imatran Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	22,	22	, "Jy-G"	, "Jyväs-Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	23,	23	, "JGs"	, "Järviseudun Golfseura");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	24,	24	, "KajG"	, "Kajaanin Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	25,	25	, "KalG"	, "Kalajokilaakson Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	26,	26	, "KarG"	, "Karelia Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	27,	27	, "KartG"	, "Kartanogolf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	28,	28	, "KatiG"	, "Katinkulta Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	29,	29	, "KeriG"	, "Kerigolf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	30,	30	, "KokG"	, "Kokkolan Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	32,	32	, "KosG"	, "Koski-Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	33,	33	, "KurG"	, "Kurk Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	35,	35	, "KyG"	, "Kymen Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	36,	36	, "LahG"	, "Lahden Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	37,	37	, "LPG"	, "Laukaan Peurunkagolf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	39,	39	, "LoG"	, "Loimijoki Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	40,	40	, "KGK"	, "Kemin Golf Klubi");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	41,	41	, "MGC"	, "Master Golf Club");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	42,	42	, "MLG"	, "Meri-Lapin Golfklubi");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	43,	43	, "MTG"	, "Meri-Teijo Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	44,	44	, "MeG"	, "Messilä Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	45,	45	, "MiG"	, "Mikkelin Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	46,	46	, "NeG"	, "Nevas Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	47,	47	, "TaG"	, "Tahko Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	48,	48	, "NCGC"	, "Nordcenter Golf & Country Club");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	49,	49	, "NGk"	, "Nurmijärven Golfklubi");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	50,	50	, "OGk"	, "Oulun Golfkerho");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	51,	51	, "OGs"	, "Outokummun Golfseura");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	52,	52	, "PaG"	, "Paltamo Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	53,	53	, "PelG"	, "Peltola Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	54,	54	, "PeG"	, "Peuramaa Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	55,	55	, "PicG"	, "Pickala Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	56,	56	, "PieG"	, "Pielis-Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	57,	57	, "JG-PG"	, "Jakobstads Golf - Pietarsaaren Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	58,	58	, "PirG"	, "Pirkanmaan Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	59,	59	, "PGk"	, "Porin Golfkerho");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	60,	60	, "TarG"	, "TarinaGolf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	61,	61	, "RaG"	, "Raahentienoon Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	62,	62	, "KanG"	, "Kankaisten Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	63,	63	, "RaG"	, "Rauma Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	64,	64	, "MuG"	, "Muurame Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	65,	65	, "PoG"	, "Porvoo Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	67,	67	, "KuG"	, "Kuusamo Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	68,	68	, "RuG"	, "Ruukkigolf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	69,	69	, "SaG"	, "Salo Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	70,	70	, "SGk"	, "Sarfvik Golfklubi ry");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	71,	71	, "RanG"	, "Rantasalmi Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	72,	72	, "SGR"	, "Sea Golf Rönnäs");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	73,	73	, "HG&C"	, "Harjattula Golf & Country Club");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	74,	74	, "ArGC"	, "Archipelagia Golf Club");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	75,	75	, "StLGC"	, "St. Lake Golf Club");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	76,	76	, "StLG"	, "St. Laurence Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	77,	77	, "SHG"	, "Suur-Helsingin Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	78,	78	, "TG"	, "Tammer-Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	79,	79	, "TawG"	, "Tawast Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	80,	80	, "TuGk"	, "Tuusulan Golfklubi");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	81,	81	, "UGK"	, "Uudenkaupungin GK");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	84,	84	, "KG"	, "Keimola Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	86,	86	, "VGs"	, "Vierumäen Golfseura");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	87,	87	, "ViG"	, "Viipurin Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	88,	88	, "VirG"	, "Virvik Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	89,	89	, "WGC"	, "Wiurila Golf & Country Club");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	90,	90	, "Y-SG"	, "Ylä-Savon Golfseura");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	91,	91	, "YG"	, "Yyteri Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	92,	92	, "ÅGk"	, "Ålands Golfklubb");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	93,	93	, "ÄG"	, "Ähtärin Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	95,	95	, "NSG"	, "Nivalan Seudun Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	96,	96	, "ViGC"	, "Vihti Golf Club");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	98,	98	, "KKG"	, "Kotojärven Kartanogolf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	99,	99	, "VGH"	, "Vuosaari Golf Helsinki");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	100,	100	, "HiG"	, "Hiisi-Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	101,	101	, "NakG"	, "Nakkila Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	102,	102	, "KuoG"	, "Kuortane Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	103,	103	, "HG&A"	, "Härmä Golf & Academy");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	104,	104	, "GPi"	, "Golf Pirkkala");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	105,	105	, "IiG"	, "Iitti Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	106,	106	, "EeG"	, "Eerikkala Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	107,	107	, "KuGC"	, "Kullo Golf Club");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	108,	108	, "KytG"	, "Kytäjä Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	109,	109	, "HatG"	, "Hattula Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	110,	110	, "HSGC"	, "Hill Side Golf & Country Club");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	111,	111	, "HirG"	, "Hirsala Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	112,	112	, "LamG"	, "Lampila Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	113,	113	, "RevG"	, "Revontuli Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	114,	114	, "ReGC"	, "Remson Golf Club");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	115,	115	, "KV"	, "Kanavagolf Vääksy");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	116,	116	, "LiG"	, "Linna Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	117,	117	, "AuG"	, "Aurinko Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	118,	118	, "HGM"	, "Hirvihaara Golf Mäntsälä");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	119,	119	, "VöG"	, "Vörå Golf - Vöyrin Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	120,	120	, "PuuG"	, "PuulaGolf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	122,	122	, "LeG"	, "Levi Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	123,	123	, "HIFK"	, "Paloheinä Golf / HIFK Golf ");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	124,	124	, "VirG"	, "Virpiniemi Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	125,	125	, "AlG"	, "Alastaro Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	126,	126	, "LeG"	, "Lepaa Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	127,	127	, "KGCN"	, "Kultaranta Golf Club Naantali ry");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	128,	128	, "TiG"	, "Tiirin Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	129,	129	, "EkeG"	, "Eke Golf ry");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	130,	130	, "KaG"	, "Kaakon Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	131,	131	, "OulG"	, "Oulujokilaakson Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	132,	132	, "HCGS"	, "Holiday Club Golf Saimaa");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	134,	134	, "TapG"	, "Tapiola Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	136,	136	, "HimG"	, "Himos-Patalahti Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	138,	138	, "VGp"	, "Vantaan Golfpuisto");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	139,	139	, "EcG"	, "Eckerö Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	140,	140	, "LöG"	, "Löfkulla Golf");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	141,	141	, "LGs"	, "Leppävirran Golfseura");

INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	83,	83	, "järvi"	, "Järvenranta");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	183,	83	, "pelto"	, "Pirunpelto");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	66,	66	, "Rock"	, "Rock");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	266,	66	, "River"	, "River");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	282,	82	, "K+S"	, "Keltainen+Sininen");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	283,	82	, "K+V"	, "Keltainen+Valkoinen");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	284,	82	, "K"	, "Keltainen");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	285,	82	, "S+V"	, "Sininen+Valkoinen");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	286,	82	, "S+K"	, "Sininen+Keltainen");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	287,	82	, "S"	, "Sininen");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	288,	82	, "V+K"	, "Valkoinen+Keltainen");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	289,	82	, "V+S"	, "Valkoinen+Sininen");
INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	290,	82	, "V"	, "Valkoinen");

INSERT INTO kentta ( `id`, `seura_id`, `kentan_lyhenne`, `kentan_nimi` ) VALUES (	999,	999	, "Edu"	, "Eduix testikenttä");


