INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	1	, "AGC"	, "Anola Golf Club");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	2	, "SCG"	, "Santa Claus Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	3	, "AulG"	, "Aulanko Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	4	, "AG"	, "Aura Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	5	, "BG"	, "Botnia Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	6	, "EGs"	, "Espoon Golfseura");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	7	, "ERG"	, "Espoo Ringside Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	8	, "EPG"	, "Etelä-Pohjanmaan Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	9	, "G-P"	, "Golf-Porrassalmi");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	10	, "GT"	, "Golf Talma");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	11	, "G-V"	, "Golf-Virrat");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	12	, "GG"	, "Gumböle Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	13	, "HG"	, "Hangon Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	14	, "HkGk"	, "Hartolan Golfklubi");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	15	, "HeGk"	, "Helsingin Golfklubi");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	16	, "HkG"	, "Hiekkaharju Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	18	, "HyG"	, "Hyvinkään Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	19	, "IkG"	, "Ikaalisten Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	20	, "ImG"	, "Imatran Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	22	, "Jy-G"	, "Jyväs-Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	23	, "JGs"	, "Järviseudun Golfseura");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	24	, "KajG"	, "Kajaanin Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	25	, "KalG"	, "Kalajokilaakson Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	26	, "KarG"	, "Karelia Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	27	, "KartG"	, "Kartanogolf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	28	, "KatiG"	, "Katinkulta Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	29	, "KeriG"	, "Kerigolf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	30	, "KokG"	, "Kokkolan Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	32	, "KosG"	, "Koski-Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	33	, "KurG"	, "Kurk Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	35	, "KyG"	, "Kymen Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	36	, "LahG"	, "Lahden Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	37	, "LPG"	, "Laukaan Peurunkagolf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	39	, "LoG"	, "Loimijoki Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	40	, "KGK"	, "Kemin Golf Klubi");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	41	, "MGC"	, "Master Golf Club");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	42	, "MLG"	, "Meri-Lapin Golfklubi");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	43	, "MTG"	, "Meri-Teijo Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	44	, "MeG"	, "Messilä Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	45	, "MiG"	, "Mikkelin Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	46	, "NeG"	, "Nevas Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	47	, "TaG"	, "Tahko Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	48	, "NCGC"	, "Nordcenter Golf & Country Club");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	49	, "NGk"	, "Nurmijärven Golfklubi");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	50	, "OGk"	, "Oulun Golfkerho");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	51	, "OGs"	, "Outokummun Golfseura");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	52	, "PaG"	, "Paltamo Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	53	, "PelG"	, "Peltola Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	54	, "PeG"	, "Peuramaa Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	55	, "PicG"	, "Pickala Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	56	, "PieG"	, "Pielis-Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	57	, "JG-PG"	, "Jakobstads Golf - Pietarsaaren Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	58	, "PirG"	, "Pirkanmaan Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	59	, "PGk"	, "Porin Golfkerho");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	60	, "TarG"	, "TarinaGolf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	61	, "RaG"	, "Raahentienoon Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	62	, "KanG"	, "Kankaisten Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	63	, "RaG"	, "Rauma Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	64	, "MuG"	, "Muurame Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	65	, "PoG"	, "Porvoo Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	66	, "NRG"	, "Nokia River Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	67	, "KuG"	, "Kuusamo Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	68	, "RuG"	, "Ruukkigolf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	69	, "SaG"	, "Salo Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	70	, "SGk"	, "Sarfvik Golfklubi ry");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	71	, "RanG"	, "Rantasalmi Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	72	, "SGR"	, "Sea Golf Rönnäs");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	73	, "HG&C"	, "Harjattula Golf & Country Club");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	74	, "ArGC"	, "Archipelagia Golf Club");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	75	, "StLGC"	, "St. Lake Golf Club");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	76	, "StLG"	, "St. Laurence Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	77	, "SHG"	, "Suur-Helsingin Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	78	, "TG"	, "Tammer-Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	79	, "TawG"	, "Tawast Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	80	, "TuGk"	, "Tuusulan Golfklubi");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	81	, "UGK"	, "Uudenkaupungin GK");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	82	, "VG"	, "Vaasan Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	83	, "LGV"	, "Lakeside Golf Vammala");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	84	, "KG"	, "Keimola Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	86	, "VGs"	, "Vierumäen Golfseura");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	87	, "ViG"	, "Viipurin Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	88	, "VirG"	, "Virvik Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	89	, "WGC"	, "Wiurila Golf & Country Club");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	90	, "Y-SG"	, "Ylä-Savon Golfseura");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	91	, "YG"	, "Yyteri Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	92	, "ÅGk"	, "Ålands Golfklubb");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	93	, "ÄG"	, "Ähtärin Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	95	, "NSG"	, "Nivalan Seudun Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	96	, "ViGC"	, "Vihti Golf Club");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	98	, "KKG"	, "Kotojärven Kartanogolf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	99	, "VGH"	, "Vuosaari Golf Helsinki");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	100	, "HiG"	, "Hiisi-Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	101	, "NakG"	, "Nakkila Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	102	, "KuoG"	, "Kuortane Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	103	, "HG&A"	, "Härmä Golf & Academy");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	104	, "GPi"	, "Golf Pirkkala");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	105	, "IiG"	, "Iitti Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	106	, "EeG"	, "Eerikkala Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	107	, "KuGC"	, "Kullo Golf Club");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	108	, "KytG"	, "Kytäjä Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	109	, "HatG"	, "Hattula Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	110	, "HSGC"	, "Hill Side Golf & Country Club");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	111	, "HirG"	, "Hirsala Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	112	, "LamG"	, "Lampila Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	113	, "RevG"	, "Revontuli Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	114	, "ReGC"	, "Remson Golf Club");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	115	, "KV"	, "Kanavagolf Vääksy");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	116	, "LiG"	, "Linna Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	117	, "AuG"	, "Aurinko Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	118	, "HGM"	, "Hirvihaara Golf Mäntsälä");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	119	, "VöG"	, "Vörå Golf - Vöyrin Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	120	, "PuuG"	, "PuulaGolf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	122	, "LeG"	, "Levi Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	123	, "HIFK"	, "Paloheinä Golf / HIFK Golf ");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	124	, "VirG"	, "Virpiniemi Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	125	, "AlG"	, "Alastaro Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	126	, "LeG"	, "Lepaa Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	127	, "KGCN"	, "Kultaranta Golf Club Naantali ry");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	128	, "TiG"	, "Tiirin Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	129	, "EkeG"	, "Eke Golf ry");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	130	, "KaG"	, "Kaakon Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	131	, "OulG"	, "Oulujokilaakson Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	132	, "HCGS"	, "Holiday Club Golf Saimaa");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	134	, "TapG"	, "Tapiola Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	136	, "HimG"	, "Himos-Patalahti Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	138	, "VGp"	, "Vantaan Golfpuisto");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	139	, "EcG"	, "Eckerö Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	140	, "LöG"	, "Löfkulla Golf");
INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	141	, "LGs"	, "Leppävirran Golfseura");

INSERT INTO seura( `id`, `lyhenne`,  `nimi` ) VALUES (	999	, "Edu"	, "Eduixin testiseura");

